onlyBuiltDependencies:
  - esbuild
  - "@biomejs/biome"
  - opencode-ai
minimumReleaseAgeExclude:
  - "@opencode-ai/sdk@1.18.11"
  - opencode-ai@1.18.11
  - opencode-darwin-arm64@1.18.11
  - opencode-darwin-x64-baseline@1.18.11
  - opencode-darwin-x64@1.18.11
  - opencode-linux-arm64-musl@1.18.11
  - opencode-linux-arm64@1.18.11
  - opencode-linux-x64-baseline-musl@1.18.11
  - opencode-linux-x64-baseline@1.18.11
  - opencode-linux-x64-musl@1.18.11
  - opencode-linux-x64@1.18.11
  - opencode-windows-arm64@1.18.11
  - opencode-windows-x64-baseline@1.18.11
  - opencode-windows-x64@1.18.11
allowBuilds:
  esbuild: true
  "@biomejs/biome": true
  opencode-ai: true
